# serverless.yml

service: api-qrcode
frameworkVersion: ">=1.1.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs6.10

package:
  include:
    - node_modules/**
    - package.json
    - handler.js

functions:
  createQRCode:
    handler: handler.endpoint
    events:
      - http:
          path: qr
          method: post
          cors: true
